/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kanosawa-huji' at '16/09/18 1:11' with Gradle 2.13
 *
 * @author kanosawa-huji, @date 16/09/18 1:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
